"""
Django settings for hangarin_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    """Parse a boolean environment variable robustly.

    Accepts 1/true/yes/on (case-insensitive) as True; anything else,
    including an unset variable, falls back to `default`. Plain string
    comparison (e.g. `== "True"`) would treat "False" as truthy, which
    must never enable DEBUG or weaken a security flag by accident.
    """
    return os.environ.get(name, str(default)).strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def _env_list(name, default=""):
    """Parse a comma-separated environment variable into a list."""
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def _env_int(name, default=0):
    """Parse an integer environment variable, falling back to `default`."""
    try:
        return int(os.environ.get(name, str(default)).strip())
    except (TypeError, ValueError):
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# NOTE: a hardcoded key was previously committed to Git. Production must set
# the DJANGO_SECRET_KEY environment variable (and the committed value must be
# treated as compromised/rotated). The fallback below is for local
# development only.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-do-not-use-in-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Robust parsing: DJANGO_DEBUG=False/0 (not just unset) disables debug.
DEBUG = _env_bool("DJANGO_DEBUG", default=True)

# Production hosts are environment-configurable; local defaults keep
# development working without extra setup. Never use ["*"] here.
ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    "127.0.0.1,localhost,erlybird21hangarin.pythonanywhere.com",
)

# Origins trusted for CSRF checks (scheme + host, e.g.
# "https://erlybird21hangarin.pythonanywhere.com"). Empty by default so
# local HTTP development keeps working; production HTTPS deployments
# must set this to the real deployment origin.
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    "tasks",
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Login / logout redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# django-allauth account settings
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

# Google/GitHub OAuth credentials are NEVER committed. Provide them via
# environment variables (local .env, which is gitignored, or production
# env config). With empty values the provider structure loads correctly
# but the flow cannot complete until real credentials are supplied.
#
# Expected environment variables:
# GOOGLE_OAUTH_CLIENT_ID / GOOGLE_OAUTH_SECRET
# GITHUB_OAUTH_CLIENT_ID / GITHUB_OAUTH_SECRET
#
# Register OAuth Apps with the callback URLs generated by django-allauth
# (allauth 65.x, provider slug + login/callback/):
# Google: https://<host>/accounts/google/login/callback/ (locally:
# http://127.0.0.1:8000/accounts/google/login/callback/)
# GitHub: https://<host>/accounts/github/login/callback/ (locally:
# http://127.0.0.1:8000/accounts/github/login/callback/)
# Configure the values outside Git (production: PythonAnywhere env config).
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_OAUTH_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "github": {
        "APP": {
            "client_id": os.environ.get("GITHUB_OAUTH_CLIENT_ID", ""),
            "secret": os.environ.get("GITHUB_OAUTH_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
    }
}

# Skip the intermediate allauth confirmation page so Hangarin login goes
# directly: login page -> provider -> provider auth UI -> Hangarin.
# Applies to Google and GitHub equally; callbacks and credentials unchanged.
SOCIALACCOUNT_LOGIN_ON_GET = True

# First-time social users are auto-created when allauth can safely do so
# (unique verified email from the provider). Existing associations log in
# directly. This is the allauth default; set explicitly to document intent.
SOCIALACCOUNT_AUTO_SIGNUP = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'hangarin_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hangarin_project.wsgi.application'


# HTTPS / security hardening. Every redirect/cookie/HSTS behavior is
# environment-controlled so local HTTP development keeps working while a
# production HTTPS deployment can enable the full set. Do NOT enable
# SECURE_SSL_REDIRECT or HSTS until the deployment actually serves HTTPS.
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", default=False)
SECURE_HSTS_SECONDS = _env_int("DJANGO_SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False
)
SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
# X_FRAME_OPTIONS keeps Django's safe default (DENY) and is
# intentionally not weakened here.


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Project-level static assets (e.g. static/css/hangarin.css). Required so
# the centralized stylesheet is served in development and collected for
# production via `collectstatic`.
STATICFILES_DIRS = [BASE_DIR / 'static']


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# NOTE (Phase 1 leftover fixed): the previous `MAILERS` dict was not a Django
# setting and had no effect. Local development uses the console backend so
# password-reset emails can be inspected in the terminal. Production should
# set DJANGO_EMAIL_BACKEND (e.g. an SMTP backend) plus the matching
# EMAIL_HOST_* variables.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL", "hangarin@localhost"
)
# Production SMTP configuration (all optional in development; the console
# backend above remains the default). Set DJANGO_EMAIL_BACKEND to
# "django.core.mail.backends.smtp.EmailBackend" plus these values to send
# real mail such as password resets. Never commit credentials.
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "localhost")
EMAIL_PORT = _env_int("DJANGO_EMAIL_PORT", default=25)
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("DJANGO_EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = _env_bool("DJANGO_EMAIL_USE_SSL", default=False)
